### ISSUE TITLE
GitPack 1.1.0 installation fails and throws E9

### ISSUE THREAD

**Issue by chw9999** [dominiksalvet/gitpack#13]
**Environment**
State GitPack version and OS information.
Error before local installation of 1.1.0 finalizes on Xubuntu 22.04 LTS 

**Description**
Describe the bug.
Does not install, throwing E9

**Replication**
State steps to replicate the bug.
-

**Additional context**
Add expected behavior or solution and any other context.
I tried installing GitPack locally, but got the following error messages. Any hints? Thanks for the tool, btw :)

christoph@ASUS-Laptop:/media/ramdisk$ wget -qO- https://raw.githubusercontent.com/dominiksalvet/gitpack/master/.install/initl.sh | sh
installing GitPack locally
>>> running install for github.com/dominiksalvet/gitpack
downloading repository
reading status database
using automatic candidate version
installing version 1.1.0
E9: missing script for local installation on Linux
repository developer may help
christoph@ASUS-Laptop:/media/ramdisk$ wget -qO- https://raw.githubusercontent.com/dominiksalvet/gitpack/master/.install/initl.sh | sh
installing GitPack locally
mkdir: das Verzeichnis »/tmp/first-gitpack/1000/“ kann nicht angelegt werden: Die Datei existiert bereits
christoph@ASUS-Laptop:/media/ramdisk$ mv /tmp/first-gitpack /tmp/first-gitpack_x
christoph@ASUS-Laptop:/media/ramdisk$ wget -qO- https://raw.githubusercontent.com/dominiksalvet/gitpack/master/.install/initl.sh | sh
installing GitPack locally
>>> running install for github.com/dominiksalvet/gitpack
local repository fresh
reading status database
using automatic candidate version
installing version 1.1.0
E9: missing script for local installation on Linux
repository developer may help
christoph@ASUS-Laptop:/media/ramdisk$ 

Regards,
Christoph

**Comment by dominiksalvet** [comment]
Hello Christoph, the first GitPack installation works as follows:

1. Helper script `initl.sh` downloads the GitPack repository to a temporary directory (which I see you have noticed) -- it is designed to allow one installation per user and system uptime (hence its temporary directory location).
2. GitPack itself is then installed using the downloaded `gitpack` script from this temporary directory (to solve the egg-chicken problem -- GitPack installs GitPack).
3. The above installation proceeds the standard way GitPack installs repositories, so it may be helpful to run `<path to gitpack script in the temporary directory> paths`.
   * This will print the paths GitPack uses for various staff, which could be helpful when debugging your issue since obviously, the `gitpack` script did not download the GitPack repository correctly, which may be the reason its local installation script is missing (while it should be present since GitPack supports local installation).
   * You should be interested in the contents of the `cache-dir`, which should include the correctly downloaded GitPack repository.

Please have a look at these and let me know if you find out something more.
